CREATE TABLE `techat`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `last_online_time` VARCHAR(50) NULL,
  `nickname` VARCHAR(50) NULL,
  `avatar` VARCHAR(150) NULL,
  `intro` VARCHAR(45) NULL,
  `user_set` VARCHAR(100) NULL,
  `phone` VARCHAR(45) NULL,
  `site` VARCHAR(100) NULL,
  `age` VARCHAR(45) NULL,
  `birthday` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  `personal_back` VARCHAR(150) NULL,
  `mail` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `password_UNIQUE` (`password` ASC) VISIBLE);
